# Setting Server Port
server.port=8103
server.servlet.context-path=/

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url=jdbc:mysql://8.222.220.102:3306/telcosms_shortlink
spring.datasource.username=david
spring.datasource.password=david_telcosms_911

## MyBatis Configuration
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.shop.bike.entity

## MULTIPART (MultipartProperties)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB

## PayPal-config
#paypal.mode=sandbox
#paypal.client.app=
#paypal.client.secret=

## Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mait70967@gmail.com
spring.mail.password=lymc carl oxtu emnk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

## Swagger
springfox.documentation.swagger-ui.enabled=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

## Spring DevTools
spring.devtools.restart.enabled=false

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

short-link.goto-domain.white-list.enable=true
short-link.goto-domain.white-list.names=??offer,??,??,???
short-link.goto-domain.white-list.details[0]=nageoffer.com
short-link.goto-domain.white-list.details[1]=zhihu.com
short-link.goto-domain.white-list.details[2]=juejin.cn
short-link.goto-domain.white-list.details[3]=cnblogs.com
