server:
  port: 8102

spring:
  application:
    name: short-link-admin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://8.222.220.102:3306/telcosms_shortlink?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: david
    password: david_telcosms_911
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 20
